### PR TITLE
Binder

### PR DESCRIPTION
**Pull request by jburel**
This PR allows to run the Fiji notebooks
Notebooks and scripts have been filtered respectively from https://github.com/ome/training-notebooks and https://github.com/ome/training-scripts.

You can also use Fiji directly in the desktop.

You can test the notebook building locally using repo2docker or mybinder

cc @dominikl @pwalczysko

### CODE REVIEW

**Comment by dominikl** [comment]
Looks good so far. Fiji on the binder desktop works fine. The crop notebook using websocket connection too 👍 All tested with repo2docker, haven't tried mybinder yet.

**Comment by dominikl** [comment]
Testing the crop_image_macro notebook. I'll get:
```
java.awt.AWTError: Can't connect to X11 window server using ':1.0' as the value of the DISPLAY variable.
	at ij.gui.ImageWindow.<init>(ImageWindow.java:68)
...
```
Thought maybe it still worked, continue with "Save the cropped image as OME-TIFF", then got 
`There are no images open` and the kernel died.

**Comment by dominikl** [comment]
Sorry, didn't have the "desktop" open. `crop_image_macro` notebook works fine now.

**Comment by dominikl** [comment]
👍 But had the same issue again. Like you mentioned I had to run it twice in order for the save ROIs step to work, weird.

**Comment by jburel** [comment]
I think the problem is in the macro file when the plugins are run headless.
Some plugins do not work well in that case

**Comment by dominikl** [comment]
👍

**Comment by jburel** [comment]
@dominikl I am going to merge this PR
Depending on time and fun with Fiji, I will look at the table I could always open a new PR

**Pull request merged**
