### PR TITLE
Pyimagej

### PR DESCRIPTION
**Pull request by jburel**
Add support for pyimagej
Add example notebook showing how to do simple operation e.g. running a macro
cc @dominikl

### CODE REVIEW

**Comment by dominikl** [comment]
Pretty cool. Works. Just needs the "desktop" running too for the macro part (similar to the other notebooks). 👍

**Comment by jburel** [comment]
Tested in mybinder and it works nicely

**Comment by dominikl** [comment]
👍 Works fine.

**Comment by jburel** [comment]
Thanks @dominikl

**Pull request merged**
